import { runPiSdkAgent } from './pi-sdk-agent.js';
import { writeFile } from 'node:fs/promises';
import type { ProjectFs } from './project-fs.js';
import type { AgentJobQueue, AgentRunPersistence } from './agent-run-contracts.js';

export type AgentRuntimeExecutionMode = 'inline' | 'worker';
export type AgentRuntimeEventChannel = 'agent' | string;

export interface AgentRuntimeEventSink {
  emit(channel: AgentRuntimeEventChannel, payload: unknown, sourceEventId?: number): void;
  noteActivity?(): void;
}

export interface AgentRuntimeRunInput {
  runId?: string;
  cwd: string;
  prompt: string;
  model?: string | null;
  reasoning?: string | null;
  imagePaths?: string[];
  uploadRoot?: string | null;
  signal?: AbortSignal;
  projectFs?: ProjectFs | null;
  events: AgentRuntimeEventSink;
}

export interface AgentRuntimeRunResult {
  aborted?: boolean;
  error?: unknown;
  resolvedModel?: string | null;
}

export interface AgentRuntime {
  readonly id: string;
  readonly executionMode: AgentRuntimeExecutionMode;
  run(input: AgentRuntimeRunInput): Promise<AgentRuntimeRunResult>;
}

export interface QueuedAgentRuntimeOptions {
  delegate: AgentRuntime;
  concurrency?: number;
}

export interface SqliteWorkerAgentRuntimeOptions {
  runStore: Pick<AgentRunPersistence, 'listRunEventsAfter' | 'getRun'>;
  jobQueue: Pick<AgentJobQueue, 'enqueueJob'>;
  pollIntervalMs?: number;
}

type QueuedJob = {
  input: AgentRuntimeRunInput;
  resolve: (result: AgentRuntimeRunResult) => void;
  reject: (error: unknown) => void;
};

const E2E_FILE = 'index.html';

function e2eHtml(prompt: string): string {
  const isFollowUp = /follow-up deterministic Pi E2E/i.test(prompt);
  const heading = isFollowUp ? 'Pi Follow-up E2E' : 'Pi Agent E2E';
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>${heading}</title>
    <style>
      body { margin: 0; font-family: Inter, system-ui, sans-serif; background: #f6f7f9; color: #1f2937; }
      main { min-height: 100vh; display: grid; place-items: center; padding: 48px; }
      section { max-width: 840px; border: 1px solid #d4d9e2; background: white; padding: 44px; border-radius: 8px; box-shadow: 0 18px 50px rgb(15 23 42 / 0.12); }
      h1 { margin: 0 0 16px; font-size: 42px; line-height: 1.05; letter-spacing: 0; }
      p { font-size: 18px; line-height: 1.6; }
      ul { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 12px; padding: 0; list-style: none; }
      li { border: 1px solid #e5e7eb; padding: 14px; border-radius: 6px; font-weight: 700; }
    </style>
  </head>
  <body>
    <main>
      <section data-od-id="pi-e2e-card">
        <h1>${heading}</h1>
        <p>Generated by the deterministic Pi-compatible E2E runtime.</p>
        <ul>
          <li>Thinking Stream Ready</li>
          <li>Tool Call Ready</li>
          <li>Tool Result Ready</li>
          <li>Docker Compose Ready</li>
        </ul>
      </section>
    </main>
  </body>
</html>
`;
}

async function runE2eFakePiAgent(input: AgentRuntimeRunInput): Promise<AgentRuntimeRunResult> {
  const html = e2eHtml(input.prompt);
  const projectFs = input.projectFs;
  input.events.noteActivity?.();
  input.events.emit('agent', { type: 'status', label: 'initializing', detail: 'e2e/fake-pi' });
  input.events.emit('agent', { type: 'thinking_start' });
  input.events.emit('agent', {
    type: 'thinking_delta',
    delta: 'Planning a deterministic Pi-style design artifact for the smoke test.',
  });
  input.events.emit('agent', { type: 'thinking_end' });
  input.events.emit('agent', {
    type: 'tool_use',
    id: 'fake-pi-write-index',
    name: 'Write',
    input: { file_path: E2E_FILE, content: html },
  });
  if (projectFs) {
    await projectFs.ensureRoot();
    await writeFile(projectFs.resolvePath(E2E_FILE), html, 'utf8');
  }
  input.events.emit('agent', {
    type: 'tool_result',
    toolUseId: 'fake-pi-write-index',
    content: `Wrote ${E2E_FILE}`,
    isError: false,
  });
  input.events.emit('agent', {
    type: 'text_delta',
    delta: `Created ${E2E_FILE} with a deterministic Pi-compatible E2E design page.`,
  });
  input.events.emit('agent', {
    type: 'usage',
    usage: { input_tokens: 1, output_tokens: 1, total_tokens: 2 },
    costUsd: 0,
  });
  return { resolvedModel: 'e2e/fake-pi' };
}

export function createE2eFakePiAgentRuntime(): AgentRuntime {
  return {
    id: 'pi-sdk:e2e-fake',
    executionMode: 'inline',
    run: runE2eFakePiAgent,
  };
}

export function createInlinePiAgentRuntime(env: NodeJS.ProcessEnv = process.env): AgentRuntime {
  if (env.OD_E2E_FAKE_PI_AGENT === '1') {
    return createE2eFakePiAgentRuntime();
  }
  const runPiSdkAgentImpl = runPiSdkAgent as unknown as (
    input: Omit<AgentRuntimeRunInput, 'events'> & {
      noteActivity?: (() => void) | null;
      send: (channel: string, payload: unknown) => void;
    },
  ) => Promise<AgentRuntimeRunResult>;
  return {
    id: 'pi-sdk',
    executionMode: 'inline',
    run: (input) => {
      const runInput = {
        cwd: input.cwd,
        prompt: input.prompt,
        model: input.model ?? null,
        reasoning: input.reasoning ?? null,
        imagePaths: input.imagePaths ?? [],
        uploadRoot: input.uploadRoot ?? null,
        projectFs: input.projectFs ?? null,
        noteActivity: input.events.noteActivity ?? null,
        send: (channel: string, payload: unknown) => input.events.emit(channel, payload),
      };
      return runPiSdkAgentImpl(
        input.signal ? { ...runInput, signal: input.signal } : runInput,
      );
    },
  };
}

export function createQueuedAgentRuntime({
  delegate,
  concurrency = 1,
}: QueuedAgentRuntimeOptions): AgentRuntime {
  const maxConcurrency = Math.max(1, Math.floor(concurrency));
  const queue: QueuedJob[] = [];
  let active = 0;

  const pump = (): void => {
    while (active < maxConcurrency && queue.length > 0) {
      const job = queue.shift()!;
      active += 1;
      void delegate.run(job.input)
        .then(job.resolve, job.reject)
        .finally(() => {
          active -= 1;
          pump();
        });
    }
  };

  return {
    id: `${delegate.id}:queued`,
    executionMode: 'worker',
    run(input) {
      if (input.signal?.aborted) return Promise.resolve({ aborted: true });
      return new Promise<AgentRuntimeRunResult>((resolve, reject) => {
        const job: QueuedJob = { input, resolve, reject };
        const abortQueued = (): void => {
          const index = queue.indexOf(job);
          if (index === -1) return;
          queue.splice(index, 1);
          resolve({ aborted: true });
        };
        if (input.signal) {
          input.signal.addEventListener('abort', abortQueued, { once: true });
        }
        queue.push(job);
        pump();
      });
    },
  };
}

export function createSqliteWorkerAgentRuntime({
  runStore,
  jobQueue,
  pollIntervalMs = 500,
}: SqliteWorkerAgentRuntimeOptions): AgentRuntime {
  return {
    id: 'pi-sdk:sqlite-worker',
    executionMode: 'worker',
    async run(input) {
      if (!input.runId) {
        return { error: new Error('sqlite worker runtime requires runId') };
      }
      const runId = input.runId;
      await jobQueue.enqueueJob(runId, {
        cwd: input.cwd,
        prompt: input.prompt,
        model: input.model ?? null,
        reasoning: input.reasoning ?? null,
        imagePaths: input.imagePaths ?? [],
        uploadRoot: input.uploadRoot ?? null,
        projectFsRoot: input.projectFs?.root ?? input.cwd,
      });

      let lastEventId = 0;
      while (!input.signal?.aborted) {
        for (const record of await runStore.listRunEventsAfter(runId, lastEventId)) {
          lastEventId = Math.max(lastEventId, record.id);
          if (record.event === 'start' || record.event === 'end') continue;
          if (record.event === 'agent') {
            input.events.emit('agent', record.data, record.id);
          } else {
            input.events.emit(record.event, record.data, record.id);
          }
        }
        const run = await runStore.getRun(runId);
        if (run?.status === 'succeeded') return { aborted: false };
        if (run?.status === 'failed') {
          return { error: new Error('worker run failed') };
        }
        if (run?.status === 'canceled') return { aborted: true };
        await new Promise((resolve) => setTimeout(resolve, pollIntervalMs));
      }
      return { aborted: true };
    },
  };
}

export function createAgentRuntimeFromEnv(
  env: NodeJS.ProcessEnv = process.env,
  options: {
    runStore?: SqliteWorkerAgentRuntimeOptions['runStore'];
    jobQueue?: SqliteWorkerAgentRuntimeOptions['jobQueue'];
  } = {},
): AgentRuntime {
  const inline = createInlinePiAgentRuntime(env);
  const mode = String(env.OD_AGENT_RUNTIME ?? '').trim().toLowerCase();
  if (mode === 'sqlite-worker') {
    if (!options.runStore || !options.jobQueue) {
      throw new Error('OD_AGENT_RUNTIME=sqlite-worker requires an agent run store and job queue');
    }
    return createSqliteWorkerAgentRuntime({
      runStore: options.runStore,
      jobQueue: options.jobQueue,
    });
  }
  if (mode === 'queued' || mode === 'queued-inline' || mode === 'worker') {
    return createQueuedAgentRuntime({
      delegate: inline,
      concurrency: Number(env.OD_AGENT_WORKER_CONCURRENCY) || 1,
    });
  }
  return inline;
}
